### ISSUE TITLE
Should the contract accept a succes status in contract_delete_delete?

### ISSUE THREAD

**Issue by ikben** [aws-cloudformation/cloudformation-cli#369]
Some apis (iirc a lot of the aws ones) do not make a distinction between a succesful delete and a failed delete because the object does not exist. Most of the time this makes sense as the end result is the same: the resource does not exist (anymore).

However the contract test requires that the code always makes a distinction between these two scenario's. This is fine for cases like https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ses/blob/master/aws-ses-configurationset/src/main/java/software/amazon/ses/configurationset/DeleteHandler.java#L32 where the called API already makes a distinction, but requires an extra read / get call for APIs where no such error is thrown (eg. DeleteKeyPair in the EC2 API).

Should this be the tested behaviour, or should the test succeed if the response is either a "not found" or a "succeeded"?

**Comment by rjlohan** [comment]
In order to provide a consistent control plane, we want these resources to throw a `NotFoundException` on `Delete` (as well as `Update` and `Read`) when an instance of the resource with the specified identifiers does not exist.

Then if the consuming service (e.g; CloudFormation) chooses to treat this behaviour as a successful `Delete`, that service can make the decision. What we don't want is to have inconsistencies in the underlying resource layer, as that leads to all sorts of downstream problems in establishing consistent provisioning behaviours or defining guarantees around outcomes.

**Comment by ikben** [comment]
Guess I'll stop trying to avoid writing code :-)
