### ISSUE TITLE
[contract tests] Soft Delete/delayed delete source fail delete contract test

### ISSUE THREAD

**Issue by ammokhov** [aws-cloudformation/cloudformation-cli#503]
This tests confirms that after delete the resource cannot appear in the subsequent list request. This is true for most of the resource but there are some exceptions. This tests will be failing for resources that cannot be immediately deleted and delete handler assumes a certain state as `deleted` interpret-able. One example would be `AWS::KMS::Key` which can only be scheduled for deletion, hence the state might be only `PendingDeletion`

> Schedules the deletion of a customer master key (CMK). You may provide a waiting period, specified in days, before deletion occurs. If you do not provide a waiting period, the default period of 30 days is used. When this operation is successful, the key state of the CMK changes to PendingDeletion.

**Comment by anshikg** [comment]
It would be helpful if you could list the test cases which are failing for you. Also, a stack trace for the ones which fail with the delete issue.

**Comment by shunjd** [comment]
We have similar issues when testing deletion for the StateMachine in Step Functions. There are two types of StateMachine, EXPRESS and STANDARD, the deletion behaviors are different. For EXPRESS, the deletion is eventual consistent, so `contract_delete_read` may fail because `read` will still return the resource if it is being called subsequently within a short interval. For STANDARD, we have a soft deletion mechanism, because in order to delete a standard statemachine, Step Functions need to first put it into DELETING status and then start to clean up all the executions (this is not in realtime and will be scheduled internally).

**Comment by ammokhov** [comment]
> We have similar issues when testing deletion for the StateMachine in Step Functions. There are two types of StateMachine, EXPRESS and STANDARD, the deletion behaviors are different. For EXPRESS, the deletion is eventual consistent, so `contract_delete_read` may fail because `read` will still return the resource if it is being called subsequently within a short interval. For STANDARD, we have a soft deletion mechanism, because in order to delete a standard statemachine, Step Functions need to first put it into DELETING status and then start to clean up all the executions (this is not in realtime and will be scheduled internally).

one of the possible and quick solutions would be to have a status check in read/list handler if status is `DELETING` a `NotFound` should be thrown

**Comment by anshikg** [comment]
As discussed in the Pull Request. These resources are not in alignment with the handler Contracts. Although, some resources do have the functionality of soft/delayed delete but, as of now this is not supported by CFN.
