### ISSUE TITLE
contract test with read only primary identifier fail because a null identifier is passed to the service

### ISSUE THREAD

**Issue by rjlohan** [aws-cloudformation/cloudformation-cli#507]
The test starts by producing a model with the `resource_client.generate_create_example` implementation. However when the resource identifier is generated by the service, it is part of the `readOnlyProperties` in the schema and cannot be generated this way. We should allow for an identifier generation strategy (or overrides, or inputs) to support this test.

**Comment by ammokhov** [comment]
what is the point of this test? to check if read handler returns not found exception? I think it's sufficient to run `contract_delete_read` which in fact has a good primary id (taken from previous actions). It's pretty hard to generate primary id using `generate_create_example` considering how strict pattern should be (it could include partition, region, and even more constratins)

**Comment by anticobalt** [comment]
Also having this issue with `contract_update_non_existent_resource` when the resource has one read-only primary identifier, and with `contract_delete_create` when the resource has two identifiers (one read-only, one create-only).

**Comment by anshikg** [comment]
@anticobalt could you elaborate more on what is happening in this test: contract_delete_create ?

**Comment by anticobalt** [comment]
@anshikg The test seems to be doing a create-delete-create-delete sequence. Both create requests succeed. The first delete also succeeds, as both the read-only and create-only identifiers are included in the delete request. The second delete fails, because the read-only identifier is null. Delete handler cannot return expected `NotFound` error because it can't look up the resource without the identifier.

The read-only identifier is the only read-only property of the resource I'm testing on.

I believe [this](https://github.com/aws-cloudformation/cloudformation-cli/issues/329) issue/merge is related.

**Comment by anshikg** [comment]
@anticobalt I see your point about the contract_delete_create I don't believe it is related to this issue. I will create a new issue for this contract test and track it there.

**Comment by ammokhov** [comment]
closing this issues as it's been addressed in #515
