### ISSUE TITLE
Testing readOnlyProperties on test

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cloudformation-cli#683]
https://github.com/aws-cloudformation/cloudformation-cli/blob/e874a82755da1511bbbc1f447a276badc2c92928/src/rpdk/core/contract/suite/handler_create.py#L55-L60

This test appears to say that is on the user to code that if `readOnlyProperties` are specified that the code should throw an error. Is there a reason the service doesn't do this on a users's behalf?  Looking at the [contracts](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test-contract.html#resource-type-test-contract-create) this appears to something the user can assume will be done for them.

**Comment by ChoiByungWook** [comment]
I believe they are tracking this here: https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/issues/102

**Comment by anshikg** [comment]
> I believe they are tracking this here: [aws-cloudformation/aws-cloudformation-resource-schema#102](https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/issues/102)

I think this is unreleated to the contract test improvement @kddejong is suggesting. Feel free to correct me if I am missing something.

**Comment by anshikg** [comment]
Checked with Kevin offline, this test is present due to language plugin inconsistencies. Closing this issue for now as this is a required test for now.

**Comment by benbridts** [comment]
I ran into this today. 

I assume that that means that the python plugin does not validate that no `readOnlyProperties` are specified.

I couldn't find an issue for that in the python plugin repository.

Is there a reason that this has to be handled by the plugins and isn't handled by the engine.

For security reasons both is probably better, but that feels more like a SHOULD fail instead of a MUST fail (in the provider I'm writing I never read the readOnlyProperties, except the PrimaryIdentifier in the ReadHandler. I'm okay with that returning SUCCESS if the engine doesn't follow the contract)
