### ISSUE TITLE
Deploy lambda with docker image using nested stack

### ISSUE THREAD

**Issue by zaro0508** [aws-cloudformation/cloudformation-cli#705]
i have a lambda that references a docker image and runs it.  It’s a pure docker conainter lambda meaning that the docker container is not packaged with the lambda.  so no src folder and files for the docker container.    I can deploy the lambda with `sam deploy --config-file samconfig.toml` without error.  The samconfig.toml file contains the reference to the docker image `image_repositories = ["DockerRunnerFunction=XXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/my-test-container"]`.  Now I want to deploy it as a cloudformation nested stack.  I looked at the CFN `AWS::CloudFormation::Stack` type  however that does not have an ImageRepositories property.  Is there a way to deploy a lambda docker as a cloudformation nested stack?

**Comment by benbridts** [comment]
Hi @zaro0508,

This repository is related to the CLI tool that helps with writing your own CloudFormation types.

That being said:
- You might be looking in the wrong place. `sam deploy` should use the `template.yaml` file by default to know what to deploy, so it's not creating a stack from a DockerFile, it's creating a stack from a CloudFormation template.
- Depending on what's in the template you might be able to upload it to S3 and use it as a property in an `AWS::CloudFormation::Stack`
- However, SAM CLI (since v1.20.0) supports nested stacks, so that might be the easier way to do it

**Comment by zaro0508** [comment]
maybe not the right place for this question.  thanks.
